apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fib-knative-built
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: build-bot
      containers:
        - image: us.icr.io/<NAMESPACE>/fib-knative
